### PR TITLE
add Wavlink WS-WN572HP3 4G

### PR DESCRIPTION
**Pull request by AiyionPrime**
Thought the style matched your repo best, hope you'll adopt this one.

Looks similar to the LTE-less original `WS-WN572HP3`:
https://www.wavlink.com/en_us/product/WL-WN572HP3_en.html

### CODE REVIEW

**Comment by belzebub40k** [comment]
Thanks for your contribution! Could you please make a few changes to align it with the other images?

- remove the branding to avoid legal issues
- make the SVG a square with the image centered and a reasonable amount of margin on the edges
- add solid white background to the PNG
- resize the PNG to 938x938 pixels

**Comment by AiyionPrime** [comment]
The branding is not their logo, but merely their brandname shifted into itself in libre franklin. But I can swap it out for sth. else.

**Comment by belzebub40k** [comment]
I'd prefer if the brandig is removed completely to have the same aesthetic across all images in this repo as well as gluon-firmware-selector.

**Comment by AiyionPrime** [comment]
- [x] remove the branding to avoid legal issues
- [x] make the SVG a square with the image centered and a reasonable amount of margin on the edges
- [x] add solid white background to the PNG
- [x] resize the PNG to 938x938 pixels (exported with that dimensions to reduce impact on quality)

**Comment by AiyionPrime** [comment]
That was fast, thank you!

I'll open a PR for the firmwareselector once the device has OpenWrt Support and an open Gluon PR.
Currently waiting for the former.
https://patchwork.ozlabs.org/project/openwrt/patch/20221130203530.3034127-2-git@aiyionpri.me/

**Pull request merged**
